FROM nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------------------------
# Base tools & NVIDIA repo keys (you already had these)
# ------------------------------------------------------------------------------
WORKDIR /home
RUN rm /etc/apt/sources.list.d/cuda.list || true
RUN apt-key del 7fa2af80 || true
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/7fa2af80.pub

RUN apt-get update && apt-get install -y \
    git wget nano sudo vim iputils-ping ssh software-properties-common \
    curl micro apt-transport-https ca-certificates lsb-release gnupg2

# ------------------------------------------------------------------------------
# >>> ROS Noetic (Ubuntu 20.04) <<<
#   - Uses keyring (no deprecated apt-key for ROS)
#   - Installs desktop-full + dev tools + common extras
#   - Initializes rosdep
# ------------------------------------------------------------------------------
# Use bash for multi-line RUNs that may source envs
SHELL ["/bin/bash", "-c"]

# Add ROS 1 apt repository with signed-by keyring
RUN mkdir -p /usr/share/keyrings && \
    curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
      | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" \
      > /etc/apt/sources.list.d/ros1-latest.list

# Install ROS Noetic (desktop-full) and tooling
RUN apt-get update && apt-get install -y \
    ros-noetic-desktop-full \
    python3-rosdep python3-rosinstall python3-rosinstall-generator \
    python3-wstool build-essential \
    python3-catkin-tools \
    # common useful Noetic packages (add/remove as needed)
    ros-noetic-cv-bridge ros-noetic-image-transport \
    ros-noetic-tf ros-noetic-tf2 ros-noetic-tf2-ros \
    ros-noetic-tf2-geometry-msgs ros-noetic-tf2-eigen \
    ros-noetic-pcl-ros ros-noetic-pcl-conversions \
    ros-noetic-navigation ros-noetic-perception \
    ros-noetic-diagnostic-updater ros-noetic-rviz && \
    rm -rf /var/lib/apt/lists/*

# rosdep init/update (as root inside container)
RUN rosdep init && rosdep update

# Environment setup for all shells
ENV ROS_DISTRO=noetic
RUN echo "source /opt/ros/noetic/setup.bash" >> /etc/bash.bashrc

# If you plan to use a catkin workspace later, uncomment as a template:
# RUN mkdir -p /root/catkin_ws/src && \
#     /bin/bash -lc "source /opt/ros/noetic/setup.bash && cd /root/catkin_ws && catkin init"

# ------------------------------------------------------------------------------
# Your existing dependencies
# ------------------------------------------------------------------------------
RUN apt update && apt-get install -y python3-opencv python3-dev ninja-build \
    dirmngr build-essential libssl-dev python3-pip python3-yaml python3-tk \
    python3-venv libboost-all-dev

RUN mkdir /home/ngd_slam

# ------------------------------------------------------------------------------
# CMake from source
# ------------------------------------------------------------------------------
WORKDIR /root
RUN mkdir temp
WORKDIR /root/temp
RUN curl -OL https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4.tar.gz
RUN tar -xzvf cmake-3.27.4.tar.gz
WORKDIR /root/temp/cmake-3.27.4
RUN ./bootstrap -- -DCMAKE_BUILD_TYPE:STRING=Release && make -j4 && make install
WORKDIR /root
RUN rm -rf temp

# ------------------------------------------------------------------------------
# OpenCV from source (CUDA-enabled)
# ------------------------------------------------------------------------------
WORKDIR /home
RUN apt -y update && apt -y install \
    libglew-dev libtiff5-dev zlib1g-dev libjpeg-dev libavcodec-dev libavformat-dev \
    libavutil-dev libpostproc-dev libswscale-dev libeigen3-dev libtbb-dev libgtk2.0-dev \
    cmake pkg-config checkinstall libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libgtkglext1 libgtkglext1-dev unzip libpng-dev libtiff-dev libv4l-dev libxvidcore-dev \
    libx264-dev libgtk-3-dev libatlas-base-dev gfortran libprotobuf-dev \
    libgoogle-glog-dev libgflags-dev libleveldb-dev liblmdb-dev python3-dev python3-numpy python3-venv

RUN cd ${HOME} && \
    wget -O opencv.zip https://github.com/opencv/opencv/archive/4.5.1.zip && \
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.1.zip && \
    unzip opencv.zip && unzip opencv_contrib.zip && \
    mv opencv-4.5.1 opencv && mv opencv_contrib-4.5.1 opencv_contrib && \
    cd ~/opencv && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_PYTHON_EXAMPLES=ON \
          -D INSTALL_C_EXAMPLES=ON \
          -D OPENCV_ENABLE_NONFREE=ON \
          -D WITH_CUDA=ON \
          -D WITH_CUDNN=ON \
          -D OPENCV_DNN_CUDA=ON \
          -D WITH_GSTREAMER=ON \
          -D WITH_GSTREAMER_0_10=OFF \
          -D WITH_OPENGL=ON \
          -D BUILD_TBB=ON \
          -D ENABLE_FAST_MATH=1 \
          -D CUDA_FAST_MATH=1 \
          -D CUDA_ARCH_BIN="6.1 7.0 7.5 8.6" \
          -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.6 \
          -D ENABLE_PRECOMPILED_HEADERS=OFF \
          -D WITH_CUBLAS=1 \
          -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
          -D HAVE_opencv_python3=ON \
          -D BUILD_EXAMPLES=ON \
          -D BUILD_opencv_cudacodec=OFF \
          -D OPENCV_GENERATE_PKGCONFIG=YES \
          .. && \
    make -j4 && make install

# ------------------------------------------------------------------------------
# Catch2
# ------------------------------------------------------------------------------
WORKDIR /home
RUN apt update && \
    git clone https://github.com/catchorg/Catch2.git && \
    cd /home/Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && cmake --build build/ --target install 

# ------------------------------------------------------------------------------
# Pangolin
# ------------------------------------------------------------------------------
WORKDIR /home/ngd_slam
RUN git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
WORKDIR /home/ngd_slam/Pangolin/build
RUN apt-get install -y libglew-dev && cmake .. && make -j20 && make install

# ------------------------------------------------------------------------------
# Eigen3
# ------------------------------------------------------------------------------
RUN apt install -y libeigen3-dev

# ------------------------------------------------------------------------------
# Python venv
# ------------------------------------------------------------------------------
WORKDIR /home/ngd_slam
RUN python3 -m venv .venv

# ------------------------------------------------------------------------------
# NGD-SLAM (files copied from build context)
# ------------------------------------------------------------------------------
WORKDIR /home/ngd_slam
# NOTE: ${PWD} is not expanded by Docker; ensure build context contains these paths
COPY ${PWD}/Examples /home/ngd_slam/Examples
COPY ${PWD}/Examples_old /home/ngd_slam/Examples_old
COPY ${PWD}/include /home/ngd_slam/include
COPY ${PWD}/src /home/ngd_slam/src
COPY ${PWD}/Vocabulary /home/ngd_slam/Vocabulary
COPY ${PWD}/build.sh /home/ngd_slam/build.sh
COPY ${PWD}/CMakeLists.txt /home/ngd_slam/CMakeLists.txt
COPY ${PWD}/evaluation /home/ngd_slam/evaluation
RUN mkdir -p Output Dataset

# ------------------------------------------------------------------------------
# Detectron2 (CUDA 11.6 pinned torch/vision)
# ------------------------------------------------------------------------------
WORKDIR /home/ngd_slam
RUN source .venv/bin/activate && \
    pip3 install --upgrade pip && \
    pip3 install torch==1.13.1+cu116 torchvision==0.14.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 && \
    pip3 install 'git+https://github.com/facebookresearch/detectron2.git@v0.5'

# ------------------------------------------------------------------------------
# Intel RealSense
# ------------------------------------------------------------------------------
WORKDIR /home
RUN apt-get update && apt-get -y upgrade && apt-get dist-upgrade -y && \
    apt-get install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev libudev-dev libusb-1.0-0-dev && \
    git clone https://github.com/IntelRealSense/librealsense.git
WORKDIR /home/librealsense
RUN mkdir build && cd build && cmake ../ -DBUILD_EXAMPLES=true && make -j4 && make install

# ------------------------------------------------------------------------------
# Thirdparty (without build folders)
# ------------------------------------------------------------------------------
COPY ${PWD}/Thirdparty/DBoW2 /home/ngd_slam/Thirdparty/DBoW2
COPY ${PWD}/Thirdparty/g2o /home/ngd_slam/Thirdparty/g2o
COPY ${PWD}/Thirdparty/Sophus /home/ngd_slam/Thirdparty/Sophus
COPY ${PWD}/Thirdparty/YOLO /home/ngd_slam/Thirdparty/YOLO
RUN rm -rf /home/ngd_slam/Thirdparty/DBoW2/build \
           /home/ngd_slam/Thirdparty/g2o/build \
           /home/ngd_slam/Thirdparty/Sophus/build \
           /home/ngd_slam/Thirdparty/YOLO/build

# ------------------------------------------------------------------------------
# Build NGD-SLAM
# ------------------------------------------------------------------------------
WORKDIR /home/ngd_slam
RUN bash build.sh
